ARG DOCKER_FFMPEG_IMAGE
ARG DOCKER_NODE_IMAGE
FROM ${DOCKER_FFMPEG_IMAGE} AS ffmpeg
FROM ${DOCKER_NODE_IMAGE}
COPY --from=ffmpeg /ffmpeg /usr/local/bin/

ENV NODE_ENV=development
RUN mkdir /app && chown node:node /app
USER node
WORKDIR /app
