version: '3.8'

services:
  backend:
    image: bastidest/video-stream-http-proxy:latest-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
    init: true
    command:
      - "bash"
      - "-c"
      - "echo 'TS_NODE_PROJECT=\"./tsconfig.json\" node --experimental-specifier-resolution=node --inspect=0.0.0.0 --loader ./node_modules/ts-node/esm ./src/server/index.ts' > ~/.bash_history && exec tail -f /dev/null"

  proxy:
    image: nginx${DOCKER_NGINX_VERSION}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
