services:
  backend:
    image: bastidest/video-stream-http-proxy:latest
    restart: unless-stopped
    ipc: host
    volumes:
      - ./config.toml:/app/config.toml:ro
  proxy:
    image: ${DOCKER_NGINX_IMAGE}
    restart: unless-stopped
    ipc: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
